// Auto-generated by @ugursahinkaya/quasar-app-extension-ssg
// This is a passthrough to @ugursahinkaya/ssg/server
export const {
  create,
  listen,
  close,
  serveStaticContent,
  renderPreloadTag
} = await import('@ugursahinkaya/ssg/server')
